common: &common
  adapter: postgresql
  username: budgeteer
  password: testing123 # from psql setup, see Postgresql

development:
  <<: *common
  database: budgeteer_development

test:
  <<: *common
  database: budgeteer_test

production:
  <<: *common
  database: budgeteer_production